# Generated by Django 5.2.8 on 2025-11-25 17:11

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=resources.models.resource_upload_path),
        ),
    ]
